/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author seif
 */
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import Technique.AdminAdapter;
import Entity.Administrateur;
import com.alee.laf.label.WebLabel;
import com.alee.managers.style.skin.ninepatch.NPLabelPainter;
import DAO.AdministrateurDAO;
import Technique.SearchAdminAdapter;
import com.alee.extended.image.WebDecoratedImage;

public class SuperGUI extends javax.swing.JPanel {

    /**
     * Creates new form SuperGUI
     */
    AdminAdapter admin = new AdminAdapter();
    AdministrateurDAO adminDAO = new AdministrateurDAO();
    public int privilege;

    public SuperGUI() {
        initComponents();
        panelAjout.setLocation(200,200);
        jTable1.setModel(new AdminAdapter());
    }

    public void updateTable() {
        jTable1.setModel(new AdminAdapter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        panelAjout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JCheckBox();
        add = new javax.swing.JCheckBox();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modify = new javax.swing.JCheckBox();
        pass = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        mail = new javax.swing.JTextField();
        repeat = new javax.swing.JTextField();

        setBackground(new java.awt.Color(241, 241, 241));

        label2.setText("Administrateur");

        jButton2.setText("recherche");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nom", "prenom", "mail", "privilège"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        panelAjout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("répetez le mot de passe");
        panelAjout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, 23));

        jLabel1.setText("nom");
        panelAjout.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        delete.setText("DELETE");
        panelAjout.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 251, -1, -1));

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        panelAjout.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, -1, -1));
        panelAjout.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 11, 249, -1));
        panelAjout.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 56, 249, -1));

        jLabel3.setText("mot de passe");
        panelAjout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, -1));

        jLabel5.setText("mail");
        panelAjout.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, -1));

        jLabel2.setText("prenom");
        panelAjout.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        modify.setText("modify");
        panelAjout.add(modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 251, -1, -1));
        panelAjout.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 102, 249, -1));

        jButton4.setText("Ajouter Admin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelAjout.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 251, 114, -1));
        panelAjout.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 204, 249, -1));
        panelAjout.add(repeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 152, 249, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                        .addGap(183, 183, 183)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(42, 42, 42))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton3)
                .addGap(59, 59, 59)
                .addComponent(panelAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "le tableau est vide");
            } else {
                JOptionPane.showMessageDialog(null, "il faut selectionner une ligne");
            }
        } else {
            int i = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");
            adminDAO.deleteAdmin(i);
            jTable1.setModel(new AdminAdapter());

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        AdministrateurDAO adminDAO = new AdministrateurDAO();
        String ch = new String();
        ch = search.getText();
        jTable1.setModel(new SearchAdminAdapter(ch));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

    }//GEN-LAST:event_addActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int i = 0;
        if (nom.getText().equals("")) {
            i = -1;
        }
        if (prenom.getText().equals("")) {
            i = -1;
        }
        if (mail.getText().equals("")) {
            i = -1;
        }
        if (pass.getText().equals("")) {
            i = -1;
        }
        if (repeat.getText().equals("")) {
            i = -1;
        }
        if (!pass.getText().equals(repeat.getText())) {
            i = -2;
            JOptionPane.showMessageDialog(null, "mot de passe incorrect!");
        }
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "il faut remplir tous les champs");
        }

        /*
         add 7
         delete 5
         modify 4
         si add+delete ==> ajout modify 77 (super)
         si add+modify==> 74  (super -delete)
         si delete+modify=> 54   (super - add)
         si add =>70 (super -modify-delete)
         si delete=> 50 (super - add -modify)
         si modify =>40 (super -add -delete)
         */
        if (add.isSelected()) {
            if (delete.isSelected()) {
                modify.setSelected(true);
                privilege = 77;
            } else if (modify.isSelected()) {
                privilege = 74;
            } else {
                privilege = 70;
            }
        } else if (delete.isSelected()) {
            if (modify.isSelected()) {
                privilege = 54;
            } else {
                privilege = 50;
            }
        } else if (modify.isSelected()) {
            privilege = 40;
        } else {
            i = -3;
        }

        if (i == -3) {
            JOptionPane.showMessageDialog(null, "il faut selectionner une privilège");
        }
        if (i == 0) {
            Administrateur admin = new Administrateur();
            admin.setNom(nom.getText());
            admin.setPrenom(prenom.getText());
            admin.setMail(mail.getText());
            admin.setPassword(pass.getText());
            admin.setPrivilege(privilege);
            AdministrateurDAO adminDAO = new AdministrateurDAO();
            adminDAO.insertAdmin(admin);
            jTable1.setModel(new AdminAdapter());
            nom.setText("");
            prenom.setText("");
            pass.setText("");
            mail.setText("");
            repeat.setText("");
            add.setSelected(false);
            modify.setSelected(false);
            delete.setSelected(false);

        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox add;
    private javax.swing.JCheckBox delete;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField mail;
    private javax.swing.JCheckBox modify;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel panelAjout;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField repeat;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
